import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

class App extends Component {
  render() {
    return (
      <div className="App">
        <div className="App-header">
          <h2>Spotagram</h2>
          <h4>photos are generated by flickr users, their titles generate songs on spotify</h4>
          <h5>click off the photos to pause</h5>
        </div>
        <p className="App-intro">
        </p>
        <div className="responsive">
          <div className="gallery">
          <img>
          </img>
          </div>
        </div>
      </div>

    );
  }
}

export default App;

// v jQuery
// (loadPics())
//
//
// $(window).load(function() {
//   var songTitle =  $("img").click(function() {
//     searchTracks(document.getElementById(this.id).alt)
//       pauseTrack()
  //     s
